import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";
// import MainPage from "./MainPage";
const MainPage = dynamic(() => import("./MainPage"), {
  ssr: false,
});
export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>이미지 변환기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </div>
  );
}
